spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12825701
spring.datasource.username=sql12825701
spring.datasource.password=Bly6efzqXA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=myTripMyChoiceSuperSecretKey2024XYZ
jwt.expiration=86400000

openrouter.api.key=${OPENROUTER_API_KEY}
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

server.port=8080
