spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12825701
spring.datasource.username=sql12825701
spring.datasource.password=Bly6efzqXA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=myTripMyChoiceSuperSecretKey2024XYZ
jwt.expiration=86400000

openrouter.api.key=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
razorpay.key.id=rzp_test_Slzxis9Y6hN5Ek
razorpay.key.secret=ywPFNIBEOMbwlATMcm515XWw

server.port=8080
